Adult child vax
mrc-ide/mpoxseir pull request #44
Opened 2024-10-21 14:46 UTC by ruthmccabe

Changes to vaccination as discussed on Friday 18/10:
- fixing bugs in assessing targets 
- child and adult vax campaigns separate
- no vax uptake parameter

2024-10-22 16:12 UTC, lwhittles requested changes
Looks great! Have left a couple of suggestions to simplify the code but looks like it's all working as expected. 🥇

2024-10-23 09:03 UTC, ruthmccabe commented on R/dust.R
> +## Generated by dust (version 0.15.2) - do not edit
done

2024-10-23 09:05 UTC, ruthmccabe commented on inst/odin/model-targeted-vax.R
> +  n_vaccination_t_S[4,2]
loooool this is so much nicer, love that my brain didn't go there at all

2024-10-23 11:03 UTC, ruthmccabe commented on inst/odin/model-targeted-vax.R
> +    1 else 0
done

2024-10-23 11:06 UTC, ruthmccabe commented
@lwhittles ready for you again when you have the chance!

2024-10-25 09:24 UTC, lwhittles approved these changes

2024-10-25 09:26 UTC, merged